#include "set.h"
/* cvrin.c */ extern void PLA_labels (pPLA PLA);
/* cvrin.c */ extern char * get_word (register FILE *fp, register char *word);
/* cvrin.c */ extern int label_index (pPLA PLA, char *word, int *varp, int *ip);
/* cvrin.c */ extern int read_pla (FILE *fp, int needs_dcset, int needs_offset, int pla_type, pPLA *PLA_return);
/* cvrin.c */ extern int read_symbolic (FILE *fp, pPLA PLA, char *word, symbolic_t **retval);
/* cvrin.c */ extern pPLA new_PLA (void);
/* cvrin.c */ extern void PLA_summary (pPLA PLA);
/* cvrin.c */ extern void free_PLA (pPLA PLA);
/* cvrin.c */ extern void parse_pla (FILE *fp, pPLA PLA);
/* cvrin.c */ extern void read_cube (register FILE *fp, pPLA PLA);
/* cvrin.c */ extern void skip_line (register FILE *fpin, register FILE *fpout, register int echo);
/* cvrm.c */ extern void foreach_output_function (pPLA PLA, int (*func)(pPLA, int), int (*func1)(pPLA, int));
/* cvrm.c */ extern int cubelist_partition (pset *T, pset **A, pset **B, unsigned int comp_debug);
/* cvrm.c */ extern int so_both_do_espresso (pPLA PLA, int i);
/* cvrm.c */ extern int so_both_do_exact (pPLA PLA, int i);
/* cvrm.c */ extern int so_both_save (pPLA PLA, int i);
/* cvrm.c */ extern int so_do_espresso (pPLA PLA, int i);
/* cvrm.c */ extern int so_do_exact (pPLA PLA, int i);
/* cvrm.c */ extern int so_save (pPLA PLA, int i);
/* cvrm.c */ extern pset_family cof_output (pset_family T, register int i);
/* cvrm.c */ extern pset_family lex_sort (pset_family T);
/* cvrm.c */ extern pset_family mini_sort (pset_family F, qsort_compare_func compare);
/* cvrm.c */ extern pset_family random_order (register pset_family F);
/* cvrm.c */ extern pset_family size_sort (pset_family T);
/* cvrm.c */ extern pset_family sort_reduce (pset_family T);
/* cvrm.c */ extern pset_family uncof_output (pset_family T, int i);
/* cvrm.c */ extern pset_family unravel (pset_family B, int start);
/* cvrm.c */ extern pset_family unravel_range (pset_family B, int start, int end);
/* cvrm.c */ extern void so_both_espresso (pPLA PLA, int strategy);
/* cvrm.c */ extern void so_espresso (pPLA PLA, int strategy);
/* cvrmisc.c */ extern char * fmt_cost (pcost cost);
/* cvrmisc.c */ extern char * print_cost (pset_family F);
/* cvrmisc.c */ extern void copy_cost (pcost s, pcost d);
/* cvrmisc.c */ extern void cover_cost (pset_family F, pcost cost);
/* cvrmisc.c */ extern void fatal (char *s);
/* cvrmisc.c */ extern void print_trace (pset_family T, char *name, long time);
/* cvrmisc.c */ extern void size_stamp (pset_family T, char *name);
/* cvrmisc.c */ extern void totals (long time, int i, pset_family T, pcost cost);
/* cvrout.c */ extern char * fmt_cube (register pset c, register char *out_map, register char *s);
/* cvrout.c */ extern char * pc1 (pset c);
/* cvrout.c */ extern char * pc2 (pset c);
/* cvrout.c */ extern void makeup_labels (pPLA PLA);
/* cvrout.c */ extern void kiss_output (FILE *fp, pPLA PLA);
/* cvrout.c */ extern void kiss_print_cube (FILE *fp, pPLA PLA, pset p, char *out_string);
/* cvrout.c */ extern void output_symbolic_constraints (FILE *fp, pPLA PLA, int output_symbolic);
/* cvrout.c */ extern void cprint (pset_family T);
/* cvrout.c */ extern void debug1_print (pset_family T, char *name, int num);
/* cvrout.c */ extern void debug_print (pset *T, char *name, int level);
/* cvrout.c */ extern void eqn_output (pPLA PLA);
/* cvrout.c */ extern void fpr_header (FILE *fp, pPLA PLA, int output_type);
/* cvrout.c */ extern void fprint_pla (FILE *fp, pPLA PLA, int output_type);
/* cvrout.c */ extern void pls_group (pPLA PLA, FILE *fp);
/* cvrout.c */ extern void pls_label (pPLA PLA, FILE *fp);
/* cvrout.c */ extern void pls_output (pPLA PLA);
/* cvrout.c */ extern void print_cube (register FILE *fp, register pset c, register char *out_map);
/* cvrout.c */ extern void print_expanded_cube (register FILE *fp, register pset c, pset phase);
